### ISSUE TITLE
Refreshing the inference window, new settings not sticking.

### ISSUE THREAD

**Issue by aboharbf** [ankilab/DeepD3#1]
I've been playing around with the website data and as I was tuning the parameters on the segmentation of activity, I notice the larger window doesn't reflect those saved settings. Below you'll see the 2 cells each partitioned into 2 ROIs, even though the settings window on the right has them as a single unit.

![image](https://user-images.githubusercontent.com/25850560/218180793-5604e97e-2e03-4361-993f-1d8c51d8139a.png)

Even when I close and reopen the application, The segmentation remains this way and the settings revert.

segment I'm working at is z: 23, x: 582, y:142

These are the files I'm working with: https://1drv.ms/u/s!Ah7iCG_uriY8spgTKuy0RaFyg3HGIA?e=gGSrZV

**Comment by TsungChihTsai** [comment]
@aboharbf  Sorry to bother you, I cannot access to the link (https://1drv.ms/u/s!Ah7iCG_uriY8spgTKuy0RaFyg3HGIA?e=gGSrZV)
