### ISSUE TITLE
several problems

### ISSUE THREAD

**Issue by Pascal-bucketbreaker** [ankilab/DeepD3#8]
1. Your tutorial does not mention the version of dependencies, so the latest version will be installed.
This causes some problems:
- astype(np.int64) is deprecated and will raise error
- skimage.feature.peak_local_max() does not have parameter "indices" and will also raise error.
2. When input is a 3-D tif image or a stack of 2-D tif image, the output can't be read by tifffile.

By the way, can I use the code as a program or 'import deepd3' then deepd3.inference(image)?

**Comment by anki-xyz** [comment]
Thank you Pascal, we look into this!
You can indeed do `import deepd3`, but you would use `from deepd3.core.analysis import Stack`, use `Stack` as an object and use the method `predictWholeImage` to get a plane-by-plane inference.

**Comment by Pascal-bucketbreaker** [comment]
The method above running successfully. However, the GPU memory does not clean up after running. After prediction, the 16GB memory is all stucked.
